name: SailfishOS Build

on: [push, pull_request]

env:
  OS_VERSION: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Build App
    strategy:
      matrix:
        arch: ['armv7hl', 'aarch64', 'i486']

    steps:
    - uses: actions/checkout@v3
      with:
	submodules: recursive

    - name: Prepare
      run: docker pull coderus/sailfishos-platform-sdk:$OS_VERSION && mkdir output

    - name: Build ${{ matrix.arch }}
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$OS_VERSION -v $GITHUB_WORKSPACE:/workspace -v $GITHUB_ACTION_PATH:/action /bin/bash -c "
	    mkdir -p build ;
	    cd build ;
	    cp -r /workspace/* .
	    sb2 -t SailfishOS-$OS_VERSION-${{ matrix.arch }} -R zypper --non-interactive ar --no-gpgcheck https://repo.sailfishos.org/obs/sailfishos:/chum/5.0_${{ matrix.arch }}/ sailfishos_chum ;
	    sb2 -t SailfishOS-$OS_VERSION-${{ matrix.arch }} -R zypper --non-interactive refresh ;
	    sb2 -t SailfishOS-$OS_VERSION-${{ matrix.arch }} -R zypper --non-interactive in -y mpris-qt5-devel libkf5archive-devel kcoreaddons-devel kdb-devel libKDb3-3 mkcal-qt5-devel libicu-devel pulseaudio-devel ninja;
	    mb2 -t SailfishOS-$OS_VERSION-${{ matrix.arch }} build ;
	    cp -r RPMS/*.rpm /workspace/RPMS
	"
    - name: Upload RPM (${{ matrix.arch }})
      uses: actions/upload-artifact@v4
      with:
        name: rpm-${{ matrix.arch }}
        path: output
